// Erweiterte Länderdaten mit Kontinenten und zusätzlichen Informationen
const COUNTRY_DATA = {
    // Europa
    de: { continent: 'europe', capital: 'Berlin', population: '83M' },
    fr: { continent: 'europe', capital: 'Paris', population: '67M' },
    it: { continent: 'europe', capital: 'Rom', population: '60M' },
    es: { continent: 'europe', capital: 'Madrid', population: '47M' },
    pt: { continent: 'europe', capital: 'Lissabon', population: '10M' },
    nl: { continent: 'europe', capital: 'Amsterdam', population: '17M' },
    be: { continent: 'europe', capital: 'Brüssel', population: '11M' },
    at: { continent: 'europe', capital: 'Wien', population: '9M' },
    ch: { continent: 'europe', capital: 'Bern', population: '9M' },
    pl: { continent: 'europe', capital: 'Warschau', population: '38M' },
    cz: { continent: 'europe', capital: 'Prag', population: '11M' },
    hu: { continent: 'europe', capital: 'Budapest', population: '10M' },
    ro: { continent: 'europe', capital: 'Bukarest', population: '19M' },
    bg: { continent: 'europe', capital: 'Sofia', population: '7M' },
    gr: { continent: 'europe', capital: 'Athen', population: '11M' },
    se: { continent: 'europe', capital: 'Stockholm', population: '10M' },
    no: { continent: 'europe', capital: 'Oslo', population: '5M' },
    dk: { continent: 'europe', capital: 'Kopenhagen', population: '6M' },
    fi: { continent: 'europe', capital: 'Helsinki', population: '6M' },
    is: { continent: 'europe', capital: 'Reykjavik', population: '0.4M' },
    ie: { continent: 'europe', capital: 'Dublin', population: '5M' },
    gb: { continent: 'europe', capital: 'London', population: '67M' },
    hr: { continent: 'europe', capital: 'Zagreb', population: '4M' },
    si: { continent: 'europe', capital: 'Ljubljana', population: '2M' },
    sk: { continent: 'europe', capital: 'Bratislava', population: '5M' },
    rs: { continent: 'europe', capital: 'Belgrad', population: '7M' },
    ua: { continent: 'europe', capital: 'Kiew', population: '44M' },
    ru: { continent: 'europe', capital: 'Moskau', population: '144M' },
    ee: { continent: 'europe', capital: 'Tallinn', population: '1M' },
    lv: { continent: 'europe', capital: 'Riga', population: '2M' },
    lt: { continent: 'europe', capital: 'Vilnius', population: '3M' },
    lu: { continent: 'europe', capital: 'Luxemburg', population: '0.6M' },
    mc: { continent: 'europe', capital: 'Monaco', population: '0.04M' },
    mt: { continent: 'europe', capital: 'Valletta', population: '0.5M' },
    cy: { continent: 'europe', capital: 'Nikosia', population: '1M' },
    al: { continent: 'europe', capital: 'Tirana', population: '3M' },
    mk: { continent: 'europe', capital: 'Skopje', population: '2M' },
    ba: { continent: 'europe', capital: 'Sarajevo', population: '3M' },
    me: { continent: 'europe', capital: 'Podgorica', population: '0.6M' },
    xk: { continent: 'europe', capital: 'Pristina', population: '2M' },
    ad: { continent: 'europe', capital: 'Andorra la Vella', population: '0.08M' },
    li: { continent: 'europe', capital: 'Vaduz', population: '0.04M' },
    sm: { continent: 'europe', capital: 'San Marino', population: '0.03M' },
    va: { continent: 'europe', capital: 'Vatikanstadt', population: '0.001M' },
    md: { continent: 'europe', capital: 'Chișinău', population: '3M' },
    by: { continent: 'europe', capital: 'Minsk', population: '9M' },

    // Asien
    cn: { continent: 'asia', capital: 'Peking', population: '1.4B' },
    jp: { continent: 'asia', capital: 'Tokio', population: '126M' },
    kr: { continent: 'asia', capital: 'Seoul', population: '52M' },
    in: { continent: 'asia', capital: 'Neu-Delhi', population: '1.4B' },
    th: { continent: 'asia', capital: 'Bangkok', population: '70M' },
    vn: { continent: 'asia', capital: 'Hanoi', population: '98M' },
    id: { continent: 'asia', capital: 'Jakarta', population: '274M' },
    my: { continent: 'asia', capital: 'Kuala Lumpur', population: '33M' },
    ph: { continent: 'asia', capital: 'Manila', population: '110M' },
    sg: { continent: 'asia', capital: 'Singapur', population: '6M' },
    pk: { continent: 'asia', capital: 'Islamabad', population: '225M' },
    bd: { continent: 'asia', capital: 'Dhaka', population: '166M' },
    lk: { continent: 'asia', capital: 'Colombo', population: '22M' },
    mm: { continent: 'asia', capital: 'Naypyidaw', population: '54M' },
    kh: { continent: 'asia', capital: 'Phnom Penh', population: '17M' },
    la: { continent: 'asia', capital: 'Vientiane', population: '7M' },
    bn: { continent: 'asia', capital: 'Bandar Seri Begawan', population: '0.4M' },
    tl: { continent: 'asia', capital: 'Dili', population: '1M' },
    mn: { continent: 'asia', capital: 'Ulaanbaatar', population: '3M' },
    np: { continent: 'asia', capital: 'Kathmandu', population: '30M' },
    bt: { continent: 'asia', capital: 'Thimphu', population: '0.8M' },
    mv: { continent: 'asia', capital: 'Malé', population: '0.5M' },
    af: { continent: 'asia', capital: 'Kabul', population: '39M' },
    kz: { continent: 'asia', capital: 'Astana', population: '19M' },
    uz: { continent: 'asia', capital: 'Taschkent', population: '34M' },
    tm: { continent: 'asia', capital: 'Aschgabat', population: '6M' },
    kg: { continent: 'asia', capital: 'Bischkek', population: '7M' },
    tj: { continent: 'asia', capital: 'Duschanbe', population: '10M' },
    kp: { continent: 'asia', capital: 'Pjöngjang', population: '26M' },
    tw: { continent: 'asia', capital: 'Taipeh', population: '24M' },
    hk: { continent: 'asia', capital: 'Hongkong', population: '7M' },
    mo: { continent: 'asia', capital: 'Macau', population: '0.7M' },
    ir: { continent: 'asia', capital: 'Teheran', population: '84M' },
    iq: { continent: 'asia', capital: 'Bagdad', population: '41M' },
    kw: { continent: 'asia', capital: 'Kuwait-Stadt', population: '4M' },
    bh: { continent: 'asia', capital: 'Manama', population: '2M' },
    om: { continent: 'asia', capital: 'Maskat', population: '5M' },
    ye: { continent: 'asia', capital: 'Sanaa', population: '30M' },
    sy: { continent: 'asia', capital: 'Damaskus', population: '18M' },
    lb: { continent: 'asia', capital: 'Beirut', population: '7M' },
    jo: { continent: 'asia', capital: 'Amman', population: '10M' },
    ps: { continent: 'asia', capital: 'Ramallah', population: '5M' },
    tr: { continent: 'asia', capital: 'Ankara', population: '85M' },
    il: { continent: 'asia', capital: 'Jerusalem', population: '9M' },
    sa: { continent: 'asia', capital: 'Riad', population: '35M' },
    ae: { continent: 'asia', capital: 'Abu Dhabi', population: '10M' },
    qa: { continent: 'asia', capital: 'Doha', population: '3M' },
    ge: { continent: 'asia', capital: 'Tiflis', population: '4M' },
    am: { continent: 'asia', capital: 'Eriwan', population: '3M' },
    az: { continent: 'asia', capital: 'Baku', population: '10M' },

    // Afrika
    za: { continent: 'africa', capital: 'Pretoria', population: '60M' },
    eg: { continent: 'africa', capital: 'Kairo', population: '104M' },
    ma: { continent: 'africa', capital: 'Rabat', population: '37M' },
    ng: { continent: 'africa', capital: 'Abuja', population: '211M' },
    ke: { continent: 'africa', capital: 'Nairobi', population: '54M' },
    dz: { continent: 'africa', capital: 'Algier', population: '44M' },
    tn: { continent: 'africa', capital: 'Tunis', population: '12M' },
    ly: { continent: 'africa', capital: 'Tripolis', population: '7M' },
    sd: { continent: 'africa', capital: 'Khartum', population: '44M' },
    ss: { continent: 'africa', capital: 'Juba', population: '11M' },
    et: { continent: 'africa', capital: 'Addis Abeba', population: '117M' },
    so: { continent: 'africa', capital: 'Mogadischu', population: '16M' },
    ug: { continent: 'africa', capital: 'Kampala', population: '47M' },
    tz: { continent: 'africa', capital: 'Dodoma', population: '61M' },
    gh: { continent: 'africa', capital: 'Accra', population: '31M' },
    ci: { continent: 'africa', capital: 'Yamoussoukro', population: '27M' },
    sn: { continent: 'africa', capital: 'Dakar', population: '17M' },
    cm: { continent: 'africa', capital: 'Yaoundé', population: '27M' },
    ao: { continent: 'africa', capital: 'Luanda', population: '33M' },
    mz: { continent: 'africa', capital: 'Maputo', population: '32M' },
    zw: { continent: 'africa', capital: 'Harare', population: '15M' },
    zm: { continent: 'africa', capital: 'Lusaka', population: '19M' },
    na: { continent: 'africa', capital: 'Windhoek', population: '3M' },
    bw: { continent: 'africa', capital: 'Gaborone', population: '2M' },
    mg: { continent: 'africa', capital: 'Antananarivo', population: '28M' },
    mu: { continent: 'africa', capital: 'Port Louis', population: '1M' },
    rw: { continent: 'africa', capital: 'Kigali', population: '13M' },
    bj: { continent: 'africa', capital: 'Porto-Novo', population: '12M' },
    tg: { continent: 'africa', capital: 'Lomé', population: '8M' },
    ml: { continent: 'africa', capital: 'Bamako', population: '21M' },
    bf: { continent: 'africa', capital: 'Ouagadougou', population: '21M' },
    ne: { continent: 'africa', capital: 'Niamey', population: '25M' },
    td: { continent: 'africa', capital: "N'Djamena", population: '17M' },
    ga: { continent: 'africa', capital: 'Libreville', population: '2M' },
    cg: { continent: 'africa', capital: 'Brazzaville', population: '6M' },
    cd: { continent: 'africa', capital: 'Kinshasa', population: '92M' },
    bi: { continent: 'africa', capital: 'Gitega', population: '12M' },
    cf: { continent: 'africa', capital: 'Bangui', population: '5M' },
    km: { continent: 'africa', capital: 'Moroni', population: '0.9M' },
    dj: { continent: 'africa', capital: 'Dschibuti', population: '1M' },
    er: { continent: 'africa', capital: 'Asmara', population: '4M' },
    sz: { continent: 'africa', capital: 'Mbabane', population: '1M' },
    gm: { continent: 'africa', capital: 'Banjul', population: '2M' },
    gn: { continent: 'africa', capital: 'Conakry', population: '13M' },
    gw: { continent: 'africa', capital: 'Bissau', population: '2M' },
    gq: { continent: 'africa', capital: 'Malabo', population: '1M' },
    ls: { continent: 'africa', capital: 'Maseru', population: '2M' },
    lr: { continent: 'africa', capital: 'Monrovia', population: '5M' },
    mw: { continent: 'africa', capital: 'Lilongwe', population: '20M' },
    mr: { continent: 'africa', capital: 'Nouakchott', population: '5M' },
    sc: { continent: 'africa', capital: 'Victoria', population: '0.1M' },
    sl: { continent: 'africa', capital: 'Freetown', population: '8M' },
    st: { continent: 'africa', capital: 'São Tomé', population: '0.2M' },
    cv: { continent: 'africa', capital: 'Praia', population: '0.6M' },

    // Amerika
    us: { continent: 'americas', capital: 'Washington', population: '331M' },
    ca: { continent: 'americas', capital: 'Ottawa', population: '38M' },
    mx: { continent: 'americas', capital: 'Mexiko-Stadt', population: '129M' },
    br: { continent: 'americas', capital: 'Brasília', population: '213M' },
    ar: { continent: 'americas', capital: 'Buenos Aires', population: '45M' },
    cl: { continent: 'americas', capital: 'Santiago', population: '19M' },
    co: { continent: 'americas', capital: 'Bogotá', population: '51M' },
    pe: { continent: 'americas', capital: 'Lima', population: '33M' },
    ve: { continent: 'americas', capital: 'Caracas', population: '28M' },
    uy: { continent: 'americas', capital: 'Montevideo', population: '3M' },
    py: { continent: 'americas', capital: 'Asunción', population: '7M' },
    ec: { continent: 'americas', capital: 'Quito', population: '18M' },
    bo: { continent: 'americas', capital: 'La Paz', population: '12M' },
    pa: { continent: 'americas', capital: 'Panama-Stadt', population: '4M' },
    cr: { continent: 'americas', capital: 'San José', population: '5M' },
    gt: { continent: 'americas', capital: 'Guatemala-Stadt', population: '18M' },
    hn: { continent: 'americas', capital: 'Tegucigalpa', population: '10M' },
    ni: { continent: 'americas', capital: 'Managua', population: '7M' },
    sv: { continent: 'americas', capital: 'San Salvador', population: '6M' },
    cu: { continent: 'americas', capital: 'Havanna', population: '11M' },
    jm: { continent: 'americas', capital: 'Kingston', population: '3M' },
    ht: { continent: 'americas', capital: 'Port-au-Prince', population: '11M' },
    do: { continent: 'americas', capital: 'Santo Domingo', population: '11M' },
    tt: { continent: 'americas', capital: 'Port of Spain', population: '1M' },
    bs: { continent: 'americas', capital: 'Nassau', population: '0.4M' },
    bb: { continent: 'americas', capital: 'Bridgetown', population: '0.3M' },
    bz: { continent: 'americas', capital: 'Belmopan', population: '0.4M' },
    gy: { continent: 'americas', capital: 'Georgetown', population: '0.8M' },
    sr: { continent: 'americas', capital: 'Paramaribo', population: '0.6M' },
    ag: { continent: 'americas', capital: "St. John's", population: '0.1M' },
    dm: { continent: 'americas', capital: 'Roseau', population: '0.07M' },
    gd: { continent: 'americas', capital: "St. George's", population: '0.1M' },
    kn: { continent: 'americas', capital: 'Basseterre', population: '0.05M' },
    lc: { continent: 'americas', capital: 'Castries', population: '0.2M' },
    vc: { continent: 'americas', capital: 'Kingstown', population: '0.1M' },

    // Ozeanien
    au: { continent: 'oceania', capital: 'Canberra', population: '26M' },
    nz: { continent: 'oceania', capital: 'Wellington', population: '5M' },
    pg: { continent: 'oceania', capital: 'Port Moresby', population: '9M' },
    fj: { continent: 'oceania', capital: 'Suva', population: '0.9M' },
    sb: { continent: 'oceania', capital: 'Honiara', population: '0.7M' },
    ws: { continent: 'oceania', capital: 'Apia', population: '0.2M' },
    vu: { continent: 'oceania', capital: 'Port Vila', population: '0.3M' },
    to: { continent: 'oceania', capital: "Nuku'alofa", population: '0.1M' },
    pw: { continent: 'oceania', capital: 'Ngerulmud', population: '0.02M' },
    fm: { continent: 'oceania', capital: 'Palikir', population: '0.1M' },
    ki: { continent: 'oceania', capital: 'Tarawa', population: '0.1M' },
    mh: { continent: 'oceania', capital: 'Majuro', population: '0.06M' },
    nr: { continent: 'oceania', capital: 'Yaren', population: '0.01M' },
    tv: { continent: 'oceania', capital: 'Funafuti', population: '0.01M' }
};

// Kontinente mit Übersetzungen
const CONTINENTS = {
    europe: { de: 'Europa', en: 'Europe', emoji: '🇪🇺' },
    asia: { de: 'Asien', en: 'Asia', emoji: '🌏' },
    africa: { de: 'Afrika', en: 'Africa', emoji: '🌍' },
    americas: { de: 'Amerika', en: 'Americas', emoji: '🌎' },
    oceania: { de: 'Ozeanien', en: 'Oceania', emoji: '🌊' }
};
