// Liste der Länder mit ihren ISO-Codes für Flaggen-URLs
const COUNTRIES = [
    { name: "Deutschland", code: "de" },
    { name: "Frankreich", code: "fr" },
    { name: "Italien", code: "it" },
    { name: "Spanien", code: "es" },
    { name: "Portugal", code: "pt" },
    { name: "Niederlande", code: "nl" },
    { name: "Belgien", code: "be" },
    { name: "Österreich", code: "at" },
    { name: "Schweiz", code: "ch" },
    { name: "Polen", code: "pl" },
    { name: "Tschechien", code: "cz" },
    { name: "Ungarn", code: "hu" },
    { name: "Rumänien", code: "ro" },
    { name: "Bulgarien", code: "bg" },
    { name: "Griechenland", code: "gr" },
    { name: "Schweden", code: "se" },
    { name: "Norwegen", code: "no" },
    { name: "Dänemark", code: "dk" },
    { name: "Finnland", code: "fi" },
    { name: "Island", code: "is" },
    { name: "Irland", code: "ie" },
    { name: "Großbritannien", code: "gb" },
    { name: "Kroatien", code: "hr" },
    { name: "Slowenien", code: "si" },
    { name: "Slowakei", code: "sk" },
    { name: "Serbien", code: "rs" },
    { name: "Ukraine", code: "ua" },
    { name: "Russland", code: "ru" },
    { name: "USA", code: "us" },
    { name: "Kanada", code: "ca" },
    { name: "Mexiko", code: "mx" },
    { name: "Brasilien", code: "br" },
    { name: "Argentinien", code: "ar" },
    { name: "Chile", code: "cl" },
    { name: "Kolumbien", code: "co" },
    { name: "Peru", code: "pe" },
    { name: "Venezuela", code: "ve" },
    { name: "China", code: "cn" },
    { name: "Japan", code: "jp" },
    { name: "Südkorea", code: "kr" },
    { name: "Indien", code: "in" },
    { name: "Thailand", code: "th" },
    { name: "Vietnam", code: "vn" },
    { name: "Indonesien", code: "id" },
    { name: "Malaysia", code: "my" },
    { name: "Philippinen", code: "ph" },
    { name: "Singapur", code: "sg" },
    { name: "Australien", code: "au" },
    { name: "Neuseeland", code: "nz" },
    { name: "Südafrika", code: "za" },
    { name: "Ägypten", code: "eg" },
    { name: "Marokko", code: "ma" },
    { name: "Nigeria", code: "ng" },
    { name: "Kenia", code: "ke" },
    { name: "Türkei", code: "tr" },
    { name: "Israel", code: "il" },
    { name: "Saudi-Arabien", code: "sa" },
    { name: "Vereinigte Arabische Emirate", code: "ae" },
    { name: "Katar", code: "qa" },
    { name: "Estland", code: "ee" },
    { name: "Lettland", code: "lv" },
    { name: "Litauen", code: "lt" },
    { name: "Luxemburg", code: "lu" },
    { name: "Monaco", code: "mc" },
    { name: "Malta", code: "mt" },
    { name: "Zypern", code: "cy" },
    { name: "Albanien", code: "al" },
    { name: "Nordmazedonien", code: "mk" },
    { name: "Bosnien und Herzegowina", code: "ba" },
    { name: "Montenegro", code: "me" },
    { name: "Kosovo", code: "xk" },
    { name: "Andorra", code: "ad" },
    { name: "Liechtenstein", code: "li" },
    { name: "San Marino", code: "sm" },
    { name: "Vatikanstadt", code: "va" },
    { name: "Moldau", code: "md" },
    { name: "Belarus", code: "by" },
    { name: "Georgien", code: "ge" },
    { name: "Armenien", code: "am" },
    { name: "Aserbaidschan", code: "az" },
    { name: "Pakistan", code: "pk" },
    { name: "Bangladesch", code: "bd" },
    { name: "Sri Lanka", code: "lk" },
    { name: "Myanmar", code: "mm" },
    { name: "Kambodscha", code: "kh" },
    { name: "Laos", code: "la" },
    { name: "Brunei", code: "bn" },
    { name: "Osttimor", code: "tl" },
    { name: "Mongolei", code: "mn" },
    { name: "Nepal", code: "np" },
    { name: "Bhutan", code: "bt" },
    { name: "Malediven", code: "mv" },
    { name: "Afghanistan", code: "af" },
    { name: "Kasachstan", code: "kz" },
    { name: "Usbekistan", code: "uz" },
    { name: "Turkmenistan", code: "tm" },
    { name: "Kirgisistan", code: "kg" },
    { name: "Tadschikistan", code: "tj" },
    { name: "Nordkorea", code: "kp" },
    { name: "Taiwan", code: "tw" },
    { name: "Hongkong", code: "hk" },
    { name: "Iran", code: "ir" },
    { name: "Irak", code: "iq" },
    { name: "Kuwait", code: "kw" },
    { name: "Bahrain", code: "bh" },
    { name: "Oman", code: "om" },
    { name: "Jemen", code: "ye" },
    { name: "Syrien", code: "sy" },
    { name: "Libanon", code: "lb" },
    { name: "Jordanien", code: "jo" },
    { name: "Palästina", code: "ps" },
    { name: "Algerien", code: "dz" },
    { name: "Tunesien", code: "tn" },
    { name: "Libyen", code: "ly" },
    { name: "Sudan", code: "sd" },
    { name: "Südsudan", code: "ss" },
    { name: "Äthiopien", code: "et" },
    { name: "Somalia", code: "so" },
    { name: "Uganda", code: "ug" },
    { name: "Tansania", code: "tz" },
    { name: "Ghana", code: "gh" },
    { name: "Elfenbeinküste", code: "ci" },
    { name: "Senegal", code: "sn" },
    { name: "Kamerun", code: "cm" },
    { name: "Angola", code: "ao" },
    { name: "Mosambik", code: "mz" },
    { name: "Simbabwe", code: "zw" },
    { name: "Sambia", code: "zm" },
    { name: "Namibia", code: "na" },
    { name: "Botswana", code: "bw" },
    { name: "Madagaskar", code: "mg" },
    { name: "Mauritius", code: "mu" },
    { name: "Ruanda", code: "rw" },
    { name: "Benin", code: "bj" },
    { name: "Togo", code: "tg" },
    { name: "Mali", code: "ml" },
    { name: "Burkina Faso", code: "bf" },
    { name: "Niger", code: "ne" },
    { name: "Tschad", code: "td" },
    { name: "Gabun", code: "ga" },
    { name: "Kongo", code: "cg" },
    { name: "Demokratische Republik Kongo", code: "cd" },
    { name: "Uruguay", code: "uy" },
    { name: "Paraguay", code: "py" },
    { name: "Ecuador", code: "ec" },
    { name: "Bolivien", code: "bo" },
    { name: "Panama", code: "pa" },
    { name: "Costa Rica", code: "cr" },
    { name: "Guatemala", code: "gt" },
    { name: "Honduras", code: "hn" },
    { name: "Nicaragua", code: "ni" },
    { name: "El Salvador", code: "sv" },
    { name: "Kuba", code: "cu" },
    { name: "Jamaika", code: "jm" },
    { name: "Haiti", code: "ht" },
    { name: "Dominikanische Republik", code: "do" },
    { name: "Trinidad und Tobago", code: "tt" },
    { name: "Bahamas", code: "bs" },
    { name: "Barbados", code: "bb" },
    { name: "Belize", code: "bz" },
    { name: "Guyana", code: "gy" },
    { name: "Suriname", code: "sr" },
    { name: "Papua-Neuguinea", code: "pg" },
    { name: "Fidschi", code: "fj" },
    { name: "Salomonen", code: "sb" },
    { name: "Samoa", code: "ws" },
    { name: "Vanuatu", code: "vu" },
    { name: "Tonga", code: "to" },
    { name: "Palau", code: "pw" },
    { name: "Mikronesien", code: "fm" },
    { name: "Burundi", code: "bi" },
    { name: "Zentralafrikanische Republik", code: "cf" },
    { name: "Komoren", code: "km" },
    { name: "Dschibuti", code: "dj" },
    { name: "Eritrea", code: "er" },
    { name: "Eswatini", code: "sz" },
    { name: "Gambia", code: "gm" },
    { name: "Guinea", code: "gn" },
    { name: "Guinea-Bissau", code: "gw" },
    { name: "Äquatorialguinea", code: "gq" },
    { name: "Lesotho", code: "ls" },
    { name: "Liberia", code: "lr" },
    { name: "Malawi", code: "mw" },
    { name: "Mauretanien", code: "mr" },
    { name: "Seychellen", code: "sc" },
    { name: "Sierra Leone", code: "sl" },
    { name: "São Tomé und Príncipe", code: "st" },
    { name: "Kap Verde", code: "cv" },
    { name: "Antigua und Barbuda", code: "ag" },
    { name: "Dominica", code: "dm" },
    { name: "Grenada", code: "gd" },
    { name: "St. Kitts und Nevis", code: "kn" },
    { name: "St. Lucia", code: "lc" },
    { name: "St. Vincent und die Grenadinen", code: "vc" },
    { name: "Kiribati", code: "ki" },
    { name: "Marshallinseln", code: "mh" },
    { name: "Nauru", code: "nr" },
    { name: "Tuvalu", code: "tv" },
    { name: "Macau", code: "mo" }
];

// Funktion um Flaggen-URL zu generieren
function getFlagUrl(countryCode) {
    return `https://flagcdn.com/w640/${countryCode}.png`;
}

// Funktion um Land nach Namen zu finden
function findCountryByName(name) {
    const normalized = name.toLowerCase().trim();
    return COUNTRIES.find(c => c.name.toLowerCase() === normalized);
}

// Autocomplete-Datenliste füllen
function populateDatalist() {
    const datalist = document.getElementById('countries');
    COUNTRIES.forEach(country => {
        const option = document.createElement('option');
        option.value = country.name;
        datalist.appendChild(option);
    });
}

// Zufälliges Land auswählen
function getRandomCountry() {
    return COUNTRIES[Math.floor(Math.random() * COUNTRIES.length)];
}
