// Liste der Länder mit mehrsprachigen Namen
const COUNTRIES = [
    { name: { de: "Deutschland", en: "Germany" }, code: "de" },
    { name: { de: "Frankreich", en: "France" }, code: "fr" },
    { name: { de: "Italien", en: "Italy" }, code: "it" },
    { name: { de: "Spanien", en: "Spain" }, code: "es" },
    { name: { de: "Portugal", en: "Portugal" }, code: "pt" },
    { name: { de: "Niederlande", en: "Netherlands" }, code: "nl" },
    { name: { de: "Belgien", en: "Belgium" }, code: "be" },
    { name: { de: "Österreich", en: "Austria" }, code: "at" },
    { name: { de: "Schweiz", en: "Switzerland" }, code: "ch" },
    { name: { de: "Polen", en: "Poland" }, code: "pl" },
    { name: { de: "Tschechien", en: "Czech Republic" }, code: "cz" },
    { name: { de: "Ungarn", en: "Hungary" }, code: "hu" },
    { name: { de: "Rumänien", en: "Romania" }, code: "ro" },
    { name: { de: "Bulgarien", en: "Bulgaria" }, code: "bg" },
    { name: { de: "Griechenland", en: "Greece" }, code: "gr" },
    { name: { de: "Schweden", en: "Sweden" }, code: "se" },
    { name: { de: "Norwegen", en: "Norway" }, code: "no" },
    { name: { de: "Dänemark", en: "Denmark" }, code: "dk" },
    { name: { de: "Finnland", en: "Finland" }, code: "fi" },
    { name: { de: "Island", en: "Iceland" }, code: "is" },
    { name: { de: "Irland", en: "Ireland" }, code: "ie" },
    { name: { de: "Großbritannien", en: "United Kingdom" }, code: "gb" },
    { name: { de: "Kroatien", en: "Croatia" }, code: "hr" },
    { name: { de: "Slowenien", en: "Slovenia" }, code: "si" },
    { name: { de: "Slowakei", en: "Slovakia" }, code: "sk" },
    { name: { de: "Serbien", en: "Serbia" }, code: "rs" },
    { name: { de: "Ukraine", en: "Ukraine" }, code: "ua" },
    { name: { de: "Russland", en: "Russia" }, code: "ru" },
    { name: { de: "USA", en: "USA" }, code: "us" },
    { name: { de: "Kanada", en: "Canada" }, code: "ca" },
    { name: { de: "Mexiko", en: "Mexico" }, code: "mx" },
    { name: { de: "Brasilien", en: "Brazil" }, code: "br" },
    { name: { de: "Argentinien", en: "Argentina" }, code: "ar" },
    { name: { de: "Chile", en: "Chile" }, code: "cl" },
    { name: { de: "Kolumbien", en: "Colombia" }, code: "co" },
    { name: { de: "Peru", en: "Peru" }, code: "pe" },
    { name: { de: "Venezuela", en: "Venezuela" }, code: "ve" },
    { name: { de: "China", en: "China" }, code: "cn" },
    { name: { de: "Japan", en: "Japan" }, code: "jp" },
    { name: { de: "Südkorea", en: "South Korea" }, code: "kr" },
    { name: { de: "Indien", en: "India" }, code: "in" },
    { name: { de: "Thailand", en: "Thailand" }, code: "th" },
    { name: { de: "Vietnam", en: "Vietnam" }, code: "vn" },
    { name: { de: "Indonesien", en: "Indonesia" }, code: "id" },
    { name: { de: "Malaysia", en: "Malaysia" }, code: "my" },
    { name: { de: "Philippinen", en: "Philippines" }, code: "ph" },
    { name: { de: "Singapur", en: "Singapore" }, code: "sg" },
    { name: { de: "Australien", en: "Australia" }, code: "au" },
    { name: { de: "Neuseeland", en: "New Zealand" }, code: "nz" },
    { name: { de: "Südafrika", en: "South Africa" }, code: "za" },
    { name: { de: "Ägypten", en: "Egypt" }, code: "eg" },
    { name: { de: "Marokko", en: "Morocco" }, code: "ma" },
    { name: { de: "Nigeria", en: "Nigeria" }, code: "ng" },
    { name: { de: "Kenia", en: "Kenya" }, code: "ke" },
    { name: { de: "Türkei", en: "Turkey" }, code: "tr" },
    { name: { de: "Israel", en: "Israel" }, code: "il" },
    { name: { de: "Saudi-Arabien", en: "Saudi Arabia" }, code: "sa" },
    { name: { de: "Vereinigte Arabische Emirate", en: "United Arab Emirates" }, code: "ae" },
    { name: { de: "Katar", en: "Qatar" }, code: "qa" },
    { name: { de: "Estland", en: "Estonia" }, code: "ee" },
    { name: { de: "Lettland", en: "Latvia" }, code: "lv" },
    { name: { de: "Litauen", en: "Lithuania" }, code: "lt" },
    { name: { de: "Luxemburg", en: "Luxembourg" }, code: "lu" },
    { name: { de: "Monaco", en: "Monaco" }, code: "mc" },
    { name: { de: "Malta", en: "Malta" }, code: "mt" },
    { name: { de: "Zypern", en: "Cyprus" }, code: "cy" },
    { name: { de: "Albanien", en: "Albania" }, code: "al" },
    { name: { de: "Nordmazedonien", en: "North Macedonia" }, code: "mk" },
    { name: { de: "Bosnien und Herzegowina", en: "Bosnia and Herzegovina" }, code: "ba" },
    { name: { de: "Montenegro", en: "Montenegro" }, code: "me" },
    { name: { de: "Kosovo", en: "Kosovo" }, code: "xk" },
    { name: { de: "Andorra", en: "Andorra" }, code: "ad" },
    { name: { de: "Liechtenstein", en: "Liechtenstein" }, code: "li" },
    { name: { de: "San Marino", en: "San Marino" }, code: "sm" },
    { name: { de: "Vatikanstadt", en: "Vatican City" }, code: "va" },
    { name: { de: "Moldau", en: "Moldova" }, code: "md" },
    { name: { de: "Belarus", en: "Belarus" }, code: "by" },
    { name: { de: "Georgien", en: "Georgia" }, code: "ge" },
    { name: { de: "Armenien", en: "Armenia" }, code: "am" },
    { name: { de: "Aserbaidschan", en: "Azerbaijan" }, code: "az" },
    { name: { de: "Pakistan", en: "Pakistan" }, code: "pk" },
    { name: { de: "Bangladesch", en: "Bangladesh" }, code: "bd" },
    { name: { de: "Sri Lanka", en: "Sri Lanka" }, code: "lk" },
    { name: { de: "Myanmar", en: "Myanmar" }, code: "mm" },
    { name: { de: "Kambodscha", en: "Cambodia" }, code: "kh" },
    { name: { de: "Laos", en: "Laos" }, code: "la" },
    { name: { de: "Brunei", en: "Brunei" }, code: "bn" },
    { name: { de: "Osttimor", en: "East Timor" }, code: "tl" },
    { name: { de: "Mongolei", en: "Mongolia" }, code: "mn" },
    { name: { de: "Nepal", en: "Nepal" }, code: "np" },
    { name: { de: "Bhutan", en: "Bhutan" }, code: "bt" },
    { name: { de: "Malediven", en: "Maldives" }, code: "mv" },
    { name: { de: "Afghanistan", en: "Afghanistan" }, code: "af" },
    { name: { de: "Kasachstan", en: "Kazakhstan" }, code: "kz" },
    { name: { de: "Usbekistan", en: "Uzbekistan" }, code: "uz" },
    { name: { de: "Turkmenistan", en: "Turkmenistan" }, code: "tm" },
    { name: { de: "Kirgisistan", en: "Kyrgyzstan" }, code: "kg" },
    { name: { de: "Tadschikistan", en: "Tajikistan" }, code: "tj" },
    { name: { de: "Nordkorea", en: "North Korea" }, code: "kp" },
    { name: { de: "Taiwan", en: "Taiwan" }, code: "tw" },
    { name: { de: "Hongkong", en: "Hong Kong" }, code: "hk" },
    { name: { de: "Iran", en: "Iran" }, code: "ir" },
    { name: { de: "Irak", en: "Iraq" }, code: "iq" },
    { name: { de: "Kuwait", en: "Kuwait" }, code: "kw" },
    { name: { de: "Bahrain", en: "Bahrain" }, code: "bh" },
    { name: { de: "Oman", en: "Oman" }, code: "om" },
    { name: { de: "Jemen", en: "Yemen" }, code: "ye" },
    { name: { de: "Syrien", en: "Syria" }, code: "sy" },
    { name: { de: "Libanon", en: "Lebanon" }, code: "lb" },
    { name: { de: "Jordanien", en: "Jordan" }, code: "jo" },
    { name: { de: "Palästina", en: "Palestine" }, code: "ps" },
    { name: { de: "Algerien", en: "Algeria" }, code: "dz" },
    { name: { de: "Tunesien", en: "Tunisia" }, code: "tn" },
    { name: { de: "Libyen", en: "Libya" }, code: "ly" },
    { name: { de: "Sudan", en: "Sudan" }, code: "sd" },
    { name: { de: "Südsudan", en: "South Sudan" }, code: "ss" },
    { name: { de: "Äthiopien", en: "Ethiopia" }, code: "et" },
    { name: { de: "Somalia", en: "Somalia" }, code: "so" },
    { name: { de: "Uganda", en: "Uganda" }, code: "ug" },
    { name: { de: "Tansania", en: "Tanzania" }, code: "tz" },
    { name: { de: "Ghana", en: "Ghana" }, code: "gh" },
    { name: { de: "Elfenbeinküste", en: "Ivory Coast" }, code: "ci" },
    { name: { de: "Senegal", en: "Senegal" }, code: "sn" },
    { name: { de: "Kamerun", en: "Cameroon" }, code: "cm" },
    { name: { de: "Angola", en: "Angola" }, code: "ao" },
    { name: { de: "Mosambik", en: "Mozambique" }, code: "mz" },
    { name: { de: "Simbabwe", en: "Zimbabwe" }, code: "zw" },
    { name: { de: "Sambia", en: "Zambia" }, code: "zm" },
    { name: { de: "Namibia", en: "Namibia" }, code: "na" },
    { name: { de: "Botswana", en: "Botswana" }, code: "bw" },
    { name: { de: "Madagaskar", en: "Madagascar" }, code: "mg" },
    { name: { de: "Mauritius", en: "Mauritius" }, code: "mu" },
    { name: { de: "Ruanda", en: "Rwanda" }, code: "rw" },
    { name: { de: "Benin", en: "Benin" }, code: "bj" },
    { name: { de: "Togo", en: "Togo" }, code: "tg" },
    { name: { de: "Mali", en: "Mali" }, code: "ml" },
    { name: { de: "Burkina Faso", en: "Burkina Faso" }, code: "bf" },
    { name: { de: "Niger", en: "Niger" }, code: "ne" },
    { name: { de: "Tschad", en: "Chad" }, code: "td" },
    { name: { de: "Gabun", en: "Gabon" }, code: "ga" },
    { name: { de: "Kongo", en: "Congo" }, code: "cg" },
    { name: { de: "Demokratische Republik Kongo", en: "Democratic Republic of the Congo" }, code: "cd" },
    { name: { de: "Uruguay", en: "Uruguay" }, code: "uy" },
    { name: { de: "Paraguay", en: "Paraguay" }, code: "py" },
    { name: { de: "Ecuador", en: "Ecuador" }, code: "ec" },
    { name: { de: "Bolivien", en: "Bolivia" }, code: "bo" },
    { name: { de: "Panama", en: "Panama" }, code: "pa" },
    { name: { de: "Costa Rica", en: "Costa Rica" }, code: "cr" },
    { name: { de: "Guatemala", en: "Guatemala" }, code: "gt" },
    { name: { de: "Honduras", en: "Honduras" }, code: "hn" },
    { name: { de: "Nicaragua", en: "Nicaragua" }, code: "ni" },
    { name: { de: "El Salvador", en: "El Salvador" }, code: "sv" },
    { name: { de: "Kuba", en: "Cuba" }, code: "cu" },
    { name: { de: "Jamaika", en: "Jamaica" }, code: "jm" },
    { name: { de: "Haiti", en: "Haiti" }, code: "ht" },
    { name: { de: "Dominikanische Republik", en: "Dominican Republic" }, code: "do" },
    { name: { de: "Trinidad und Tobago", en: "Trinidad and Tobago" }, code: "tt" },
    { name: { de: "Bahamas", en: "Bahamas" }, code: "bs" },
    { name: { de: "Barbados", en: "Barbados" }, code: "bb" },
    { name: { de: "Belize", en: "Belize" }, code: "bz" },
    { name: { de: "Guyana", en: "Guyana" }, code: "gy" },
    { name: { de: "Suriname", en: "Suriname" }, code: "sr" },
    { name: { de: "Papua-Neuguinea", en: "Papua New Guinea" }, code: "pg" },
    { name: { de: "Fidschi", en: "Fiji" }, code: "fj" },
    { name: { de: "Salomonen", en: "Solomon Islands" }, code: "sb" },
    { name: { de: "Samoa", en: "Samoa" }, code: "ws" },
    { name: { de: "Vanuatu", en: "Vanuatu" }, code: "vu" },
    { name: { de: "Tonga", en: "Tonga" }, code: "to" },
    { name: { de: "Palau", en: "Palau" }, code: "pw" },
    { name: { de: "Mikronesien", en: "Micronesia" }, code: "fm" },
    { name: { de: "Burundi", en: "Burundi" }, code: "bi" },
    { name: { de: "Zentralafrikanische Republik", en: "Central African Republic" }, code: "cf" },
    { name: { de: "Komoren", en: "Comoros" }, code: "km" },
    { name: { de: "Dschibuti", en: "Djibouti" }, code: "dj" },
    { name: { de: "Eritrea", en: "Eritrea" }, code: "er" },
    { name: { de: "Eswatini", en: "Eswatini" }, code: "sz" },
    { name: { de: "Gambia", en: "Gambia" }, code: "gm" },
    { name: { de: "Guinea", en: "Guinea" }, code: "gn" },
    { name: { de: "Guinea-Bissau", en: "Guinea-Bissau" }, code: "gw" },
    { name: { de: "Äquatorialguinea", en: "Equatorial Guinea" }, code: "gq" },
    { name: { de: "Lesotho", en: "Lesotho" }, code: "ls" },
    { name: { de: "Liberia", en: "Liberia" }, code: "lr" },
    { name: { de: "Malawi", en: "Malawi" }, code: "mw" },
    { name: { de: "Mauretanien", en: "Mauritania" }, code: "mr" },
    { name: { de: "Seychellen", en: "Seychelles" }, code: "sc" },
    { name: { de: "Sierra Leone", en: "Sierra Leone" }, code: "sl" },
    { name: { de: "São Tomé und Príncipe", en: "São Tomé and Príncipe" }, code: "st" },
    { name: { de: "Kap Verde", en: "Cape Verde" }, code: "cv" },
    { name: { de: "Antigua und Barbuda", en: "Antigua and Barbuda" }, code: "ag" },
    { name: { de: "Dominica", en: "Dominica" }, code: "dm" },
    { name: { de: "Grenada", en: "Grenada" }, code: "gd" },
    { name: { de: "St. Kitts und Nevis", en: "Saint Kitts and Nevis" }, code: "kn" },
    { name: { de: "St. Lucia", en: "Saint Lucia" }, code: "lc" },
    { name: { de: "St. Vincent und die Grenadinen", en: "Saint Vincent and the Grenadines" }, code: "vc" },
    { name: { de: "Kiribati", en: "Kiribati" }, code: "ki" },
    { name: { de: "Marshallinseln", en: "Marshall Islands" }, code: "mh" },
    { name: { de: "Nauru", en: "Nauru" }, code: "nr" },
    { name: { de: "Tuvalu", en: "Tuvalu" }, code: "tv" },
    { name: { de: "Macau", en: "Macau" }, code: "mo" }
];

// Helper-Funktionen
function getFlagUrl(code) {
    return `https://flagcdn.com/w640/${code}.png`;
}

function getCountryName(country, lang = 'de') {
    return country.name[lang] || country.name.de;
}

function findCountryByName(name, lang = 'de') {
    const normalized = name.toLowerCase().trim();
    return COUNTRIES.find(c => getCountryName(c, lang).toLowerCase() === normalized);
}

function getRandomCountry() {
    return COUNTRIES[Math.floor(Math.random() * COUNTRIES.length)];
}

function populateDatalist(lang = 'de') {
    const datalist = document.getElementById('countries');
    if (!datalist) return;
    
    datalist.innerHTML = '';
    const fragment = document.createDocumentFragment();
    
    COUNTRIES.forEach(country => {
        const option = document.createElement('option');
        option.value = getCountryName(country, lang);
        fragment.appendChild(option);
    });
    
    datalist.appendChild(fragment);
}
